### ISSUE TITLE
Update Community Servers page with correct URLs

### ISSUE THREAD

**Issue by monicacecilia** [genomearchitect/genomearchitect.github.io#4]
@nathandunn All links listed in the '[Community Servers' page](http://genomearchitect.github.io/communityservers/) go to the same JBrowse instance. I *think* these are human data?  The JBrowse window does not include the label with the organism.
We need to update this accordingly. Either remove the other links or update to mouse and zebrafish server.

**Comment by monicacecilia** [comment]
This is bizarre, but I just got the URLs to go to the expected servers. No idea what happened. 
Still, it would be good to have labels on the JBrowse window.

**Comment by monicacecilia** [comment]
@nathandunn I can't remember now - did you also want this on the GMOD/Apollo repo?

**Comment by nathandunn** [comment]
I have it in my personal trello board.  I'll take a look at it, but probably won't be until next week.

**Comment by monicacecilia** [comment]
Got it. Since it was such a fluke, there isn't much urgency to look into it, no worries.

**Comment by nathandunn** [comment]
I think that this is related to https://github.com/GMOD/Apollo/issues/1755.
